module.exports = [// 🌾 Commodities
      { symbol: 'CL=F', name: 'Petróleo', sector: 'Materias Primas', macroCategory: 'Materias Primas', region: 'Commodities', currency: 'USD', type: 'Commodity' },
      { symbol: 'GC=F', name: 'Oro', sector: 'Materias Primas', macroCategory: 'Materias Primas', region: 'Commodities', currency: 'USD', type: 'Commodity' },
      { symbol: 'SI=F', name: 'Plata', sector: 'Materias Primas', macroCategory: 'Materias Primas', region: 'Commodities', currency: 'USD', type: 'Commodity' },
      { symbol: 'HG=F', name: 'Cobre', sector: 'Materias Primas', macroCategory: 'Materias Primas', region: 'Commodities', currency: 'USD', type: 'Commodity' },
      { symbol: 'ZS=F', name: 'Soja', sector: 'Materias Primas', macroCategory: 'Materias Primas', region: 'Commodities', currency: 'USD', type: 'Commodity' },
      { symbol: 'ZW=F', name: 'Trigo', sector: 'Materias Primas', macroCategory: 'Materias Primas', region: 'Commodities', currency: 'USD', type: 'Commodity' },
      { symbol: 'ZC=F', name: 'Maíz', sector: 'Materias Primas', macroCategory: 'Materias Primas', region: 'Commodities', currency: 'USD', type: 'Commodity' },
      { symbol: 'NG=F', name: 'Gas Natural', sector: 'Materias Primas', macroCategory: 'Materias Primas', region: 'Commodities', currency: 'USD', type: 'Commodity' },

      // 📊 ETFs (Vista General)
      { symbol: 'SPY', name: 'SPDR S&P 500', sector: 'ETF', macroCategory: 'Índices', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'QQQ', name: 'Invesco QQQ Trust', sector: 'ETF', macroCategory: 'Índices', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'DIA', name: 'SPDR Dow Jones Industrial Average', sector: 'ETF', macroCategory: 'Índices', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'IWM', name: 'iShares Russell 2000 ETF', sector: 'ETF', macroCategory: 'Índices', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'VTI', name: 'Vanguard Total Stock Market', sector: 'ETF', macroCategory: 'Índices', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'VOO', name: 'Vanguard S&P 500 ETF', sector: 'ETF', macroCategory: 'Índices', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'TQQQ', name: 'ProShares UltraPro QQQ', sector: 'ETF', macroCategory: 'Índices', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'PSQ', name: 'ProShares Short QQQ', sector: 'ETF', macroCategory: 'Índices', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'EWZ', name: 'iShares MSCI Brazil ETF', sector: 'ETF', macroCategory: 'Países', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'EWJ', name: 'iShares MSCI Japan ETF', sector: 'ETF', macroCategory: 'Países', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'EWY', name: 'iShares MSCI South Korea ETF', sector: 'ETF', macroCategory: 'Países', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'EWW', name: 'iShares MSCI Mexico ETF', sector: 'ETF', macroCategory: 'Países', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'INDA', name: 'iShares MSCI India ETF', sector: 'ETF', macroCategory: 'Países', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'ARGT', name: 'Global X MSCI Argentina ETF', sector: 'ETF', macroCategory: 'Países', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'MCHI', name: 'iShares MSCI China ETF', sector: 'ETF', macroCategory: 'Países', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'GLD', name: 'SPDR Gold Shares', sector: 'ETF', macroCategory: 'Materias Primas', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'SLV', name: 'iShares Silver Trust', sector: 'ETF', macroCategory: 'Materias Primas', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'XLE', name: 'Energy Select Sector SPDR', sector: 'ETF', macroCategory: 'Sectores', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'XLF', name: 'Financial Select Sector SPDR', sector: 'ETF', macroCategory: 'Sectores', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'XLK', name: 'Technology Select Sector SPDR', sector: 'ETF', macroCategory: 'Sectores', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'XLY', name: 'Consumer Discretionary Select Sector', sector: 'ETF', macroCategory: 'Sectores', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'XLC', name: 'Communication Services Select Sector', sector: 'ETF', macroCategory: 'Sectores', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'XLI', name: 'Industrial Select Sector SPDR', sector: 'ETF', macroCategory: 'Sectores', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'XLV', name: 'Health Care Select Sector SPDR', sector: 'ETF', macroCategory: 'Sectores', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'XLP', name: 'Consumer Staples Select Sector', sector: 'ETF', macroCategory: 'Sectores', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'XLU', name: 'Utilities Select Sector SPDR', sector: 'ETF', macroCategory: 'Sectores', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'XLRE', name: 'Real Estate Select Sector SPDR', sector: 'ETF', macroCategory: 'Sectores', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'XLB', name: 'Materials Select Sector SPDR', sector: 'ETF', macroCategory: 'Sectores', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'IGV', name: 'iShares Expanded Tech-Software', sector: 'ETF', macroCategory: 'Sectores', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'SMH', name: 'VanEck Semiconductor ETF', sector: 'ETF', macroCategory: 'Sectores', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'ARKK', name: 'ARK Innovation ETF', sector: 'ETF', macroCategory: 'Temáticos', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'AAPL', name: 'Apple Inc.', sector: 'Software', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'MSFT', name: 'Microsoft Corporation', sector: 'Software', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'GOOGL', name: 'Alphabet Inc. (Google)', sector: 'Software', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'META', name: 'Meta Platforms Inc.', sector: 'Software', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'NVDA', name: 'NVIDIA Corporation', sector: 'Semiconductores', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'AMD', name: 'Advanced Micro Devices', sector: 'Semiconductores', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'INTC', name: 'Intel Corporation', sector: 'Semiconductores', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'QCOM', name: 'Qualcomm Inc.', sector: 'Semiconductores', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'ADBE', name: 'Adobe Inc.', sector: 'Software', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'CRM', name: 'Salesforce Inc.', sector: 'Software', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'ORCL', name: 'Oracle Corporation', sector: 'Software', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'NOW', name: 'ServiceNow Inc.', sector: 'Software', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'SNOW', name: 'Snowflake Inc.', sector: 'Software', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'PLTR', name: 'Palantir Technologies Inc.', sector: 'Software', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'COIN', name: 'Coinbase Global Inc.', sector: 'Financiero', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'IBM', name: 'IBM Corporation', sector: 'Software', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'CSCO', name: 'Cisco Systems', sector: 'Software', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'PANW', name: 'Palo Alto Networks', sector: 'Software', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'AMZN', name: 'Amazon.com Inc.', sector: 'Consumo Discrecional', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'BKNG', name: 'Booking Holdings Inc.', sector: 'Consumo Discrecional', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'ABNB', name: 'Airbnb Inc.', sector: 'Consumo Discrecional', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'EBAY', name: 'eBay Inc.', sector: 'Consumo Discrecional', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'COST', name: 'Costco Wholesale', sector: 'Consumo Básico', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'HD', name: 'Home Depot', sector: 'Consumo Discrecional', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'MCD', name: "McDonald's Corp.", sector: 'Consumo Discrecional', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'SBUX', name: 'Starbucks Corp.', sector: 'Consumo Discrecional', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'NKE', name: 'Nike Inc.', sector: 'Consumo Discrecional', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'KO', name: 'Coca-Cola Company', sector: 'Consumo Básico', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'PEP', name: 'PepsiCo Inc.', sector: 'Consumo Básico', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'F', name: 'Ford Motor Company', sector: 'Consumo Discrecional', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'GM', name: 'General Motors', sector: 'Consumo Discrecional', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'NFLX', name: 'Netflix Inc.', sector: 'Comunicaciones', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'RBLX', name: 'Roblox Corporation', sector: 'Comunicaciones', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'EA', name: 'Electronic Arts Inc.', sector: 'Comunicaciones', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'JPM', name: 'JPMorgan Chase & Co.', sector: 'Financiero', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'BAC', name: 'Bank of America Corp.', sector: 'Financiero', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'C', name: 'Citigroup Inc.', sector: 'Financiero', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'GS', name: 'Goldman Sachs Group', sector: 'Financiero', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'MA', name: 'Mastercard Inc.', sector: 'Financiero', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'AXP', name: 'American Express', sector: 'Financiero', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'PYPL', name: 'PayPal Holdings', sector: 'Financiero', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'BRKB', name: 'Berkshire Hathaway Inc.', sector: 'Financiero', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'JNJ', name: 'Johnson & Johnson', sector: 'Salud', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'PFE', name: 'Pfizer Inc.', sector: 'Salud', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'MRK', name: 'Merck & Co.', sector: 'Salud', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'LLY', name: 'Eli Lilly and Co.', sector: 'Salud', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'ABBV', name: 'AbbVie Inc.', sector: 'Salud', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'GILD', name: 'Gilead Sciences Inc.', sector: 'Salud', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'MRNA', name: 'Moderna Inc.', sector: 'Salud', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'ISRG', name: 'Intuitive Surgical Inc.', sector: 'Salud', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'HIMS', name: 'Hims & Hers Health Inc.', sector: 'Salud', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'CVX', name: 'Chevron Corporation', sector: 'Energía', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'COP', name: 'ConocoPhillips', sector: 'Energía', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'OXY', name: 'Occidental Petroleum Corp.', sector: 'Energía', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'SLB', name: 'SLB (Schlumberger)', sector: 'Energía', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'BA', name: 'Boeing Company', sector: 'Industrial', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'LMT', name: 'Lockheed Martin Corporation', sector: 'Industrial', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'RTX', name: 'RTX Corporation (Raytheon)', sector: 'Industrial', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'CAT', name: 'Caterpillar Inc.', sector: 'Industrial', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'DE', name: 'Deere & Company', sector: 'Industrial', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'GE', name: 'GE Aerospace', sector: 'Industrial', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'MELI', name: 'MercadoLibre Inc.', sector: 'Consumo Discrecional', region: 'AR', currency: 'USD', type: 'Equity' },
      { symbol: 'GLOB', name: 'Globant S.A.', sector: 'Software', region: 'AR', currency: 'USD', type: 'Equity' },
      { symbol: 'PBR', name: 'Petrobras ADR', sector: 'Energía', region: 'BR', currency: 'USD', type: 'Equity' },
      { symbol: 'VALE', name: 'Vale S.A.', sector: 'Materiales', region: 'BR', currency: 'USD', type: 'Equity' },
      { symbol: 'ITUB', name: 'Itaú Unibanco Holding S.A.', sector: 'Financiero', region: 'BR', currency: 'USD', type: 'Equity' },
      { symbol: 'BBDC', name: 'Banco Bradesco S.A.', sector: 'Financiero', region: 'BR', currency: 'USD', type: 'Equity' },
      { symbol: 'NU', name: 'Nu Holdings Ltd. (Nubank)', sector: 'Financiero', region: 'BR', currency: 'USD', type: 'Equity' },
      { symbol: 'ABEV', name: 'Ambev S.A.', sector: 'Consumo Básico', region: 'BR', currency: 'USD', type: 'Equity' },
      { symbol: 'SID', name: 'Companhia Siderúrgica Nacional (CSN)', sector: 'Materiales', region: 'BR', currency: 'USD', type: 'Equity' },
      { symbol: 'BABA', name: 'Alibaba Group Holding Ltd.', sector: 'Consumo Discrecional', region: 'CN', currency: 'USD', type: 'Equity' },
      { symbol: 'JD', name: 'JD.com Inc.', sector: 'Consumo Discrecional', region: 'CN', currency: 'USD', type: 'Equity' },
      { symbol: 'PDD', name: 'PDD Holdings (Pinduoduo)', sector: 'Consumo Discrecional', region: 'CN', currency: 'USD', type: 'Equity' },
      { symbol: 'BIDU', name: 'Baidu Inc.', sector: 'Software', region: 'CN', currency: 'USD', type: 'Equity' },
      { symbol: 'NTES', name: 'NetEase Inc.', sector: 'Software', region: 'CN', currency: 'USD', type: 'Equity' },
      { symbol: 'NIO', name: 'NIO Inc.', sector: 'Consumo Discrecional', region: 'CN', currency: 'USD', type: 'Equity' },
      { symbol: 'ASML', name: 'ASML Holding N.V.', sector: 'Semiconductores', region: 'EU', currency: 'USD', type: 'Equity' },
      { symbol: 'SAP', name: 'SAP SE', sector: 'Software', region: 'EU', currency: 'USD', type: 'Equity' },
      { symbol: 'NVO', name: 'Novo Nordisk A/S', sector: 'Salud', region: 'EU', currency: 'USD', type: 'Equity' },
      { symbol: 'AZN', name: 'AstraZeneca PLC', sector: 'Salud', region: 'EU', currency: 'USD', type: 'Equity' },
      { symbol: 'NVS', name: 'Novartis AG', sector: 'Salud', region: 'EU', currency: 'USD', type: 'Equity' },
      { symbol: 'GSK', name: 'GSK plc', sector: 'Salud', region: 'EU', currency: 'USD', type: 'Equity' },
      { symbol: 'SHEL', name: 'Shell plc', sector: 'Energía', region: 'EU', currency: 'USD', type: 'Equity' },
      { symbol: 'BP', name: 'BP plc', sector: 'Energía', region: 'EU', currency: 'USD', type: 'Equity' },
      { symbol: 'SIEGY', name: 'Siemens AG', sector: 'Industrial', region: 'EU', currency: 'USD', type: 'Equity' },
      { symbol: 'HMC', name: 'Honda Motor Co. Ltd.', sector: 'Consumo Discrecional', region: 'JP', currency: 'USD', type: 'Equity' },
      { symbol: 'SONY', name: 'Sony Group Corporation', sector: 'Consumo Discrecional', region: 'JP', currency: 'USD', type: 'Equity' },
      { symbol: 'INFY', name: 'Infosys Limited', sector: 'Software', region: 'IN', currency: 'USD', type: 'Equity' },
      { symbol: 'HDB', name: 'HDFC Bank Limited', sector: 'Financiero', region: 'IN', currency: 'USD', type: 'Equity' },
      { symbol: 'IBN', name: 'ICICI Bank Limited', sector: 'Financiero', region: 'IN', currency: 'USD', type: 'Equity' },
      { symbol: 'BTC', name: 'Bitcoin', sector: 'Criptomonedas', region: 'Global', currency: 'USD', type: 'Crypto' },
      { symbol: 'ETH', name: 'Ethereum', sector: 'Criptomonedas', region: 'Global', currency: 'USD', type: 'Crypto' },
      { symbol: 'SOL-USD', name: 'Solana', sector: 'Criptomonedas', region: 'Global', currency: 'USD', type: 'Crypto' },
      { symbol: 'TXN', name: 'Texas Instruments', sector: 'Semiconductores', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'KLAC', name: 'KLA Corporation', sector: 'Semiconductores', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'ON', name: 'ON Semiconductor Corp', sector: 'Semiconductores', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'TSM', name: 'Taiwan Semiconductor', sector: 'Semiconductores', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'TSLA', name: 'Tesla Inc', sector: 'Consumo Discrecional', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'UBER', name: 'Uber Technologies', sector: 'Software', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'SPOT', name: 'Spotify Technology S.A.', sector: 'Comunicaciones', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'CRWD', name: 'CrowdStrike Holdings', sector: 'Software', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'DDOG', name: 'Datadog Inc', sector: 'Software', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'NET', name: 'Cloudflare Inc', sector: 'Software', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'MDB', name: 'MongoDB Inc', sector: 'Software', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'ZS', name: 'Zscaler Inc', sector: 'Software', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'WDAY', name: 'Workday Inc', sector: 'Software', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'INTU', name: 'Intuit Inc', sector: 'Software', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'ADSK', name: 'Autodesk Inc', sector: 'Software', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'TEAM', name: 'Atlassian Corp', sector: 'Software', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'V', name: 'Visa Inc', sector: 'Financiero', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'UNH', name: 'UnitedHealth Group', sector: 'Salud', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'TMO', name: 'Thermo Fisher Scientific', sector: 'Salud', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'VRTX', name: 'Vertex Pharmaceuticals', sector: 'Salud', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'REGN', name: 'Regeneron Pharmaceuticals', sector: 'Salud', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'SYK', name: 'Stryker Corp', sector: 'Salud', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'WMT', name: 'Walmart Inc', sector: 'Consumo Básico', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'TGT', name: 'Target Corp', sector: 'Consumo Discrecional', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'LOW', name: "Lowe's Companies", sector: 'Consumo Discrecional', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'DIS', name: 'The Walt Disney Co', sector: 'Comunicaciones', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'XOM', name: 'Exxon Mobil Corp', sector: 'Energía', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'UPS', name: 'United Parcel Service', sector: 'Industrial', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'UAL', name: 'United Airlines', sector: 'Industrial', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'HOOD', name: 'Robinhood Markets', sector: 'Financiero', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'COPX', name: 'Global X Copper Miners ETF', sector: 'ETF', macroCategory: 'Materias Primas', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'CPER', name: 'United States Copper Index Fund', sector: 'ETF', macroCategory: 'Materias Primas', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'USO', name: 'United States Oil Fund', sector: 'ETF', macroCategory: 'Materias Primas', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'UNG', name: 'United States Natural Gas Fund', sector: 'ETF', macroCategory: 'Materias Primas', region: 'US', currency: 'USD', type: 'ETF' },
      { symbol: 'SPCX', name: 'SpaceX', sector: 'Industrial', macroCategory: 'Empresas', region: 'US', currency: 'USD', type: 'Equity' },
      // --- Missing CEDEARs added ---
      { symbol: 'C', name: 'Citigroup Inc.', sector: 'Financiero', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'BAC', name: 'Bank of America Corp', sector: 'Financiero', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'WFC', name: 'Wells Fargo & Co.', sector: 'Financiero', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'USB', name: 'U.S. Bancorp', sector: 'Financiero', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'SPGI', name: 'S&P Global Inc.', sector: 'Financiero', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'MRSH', name: 'Marsh & McLennan Companies', sector: 'Financiero', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'XP', name: 'XP Inc.', sector: 'Financiero', region: 'BR', currency: 'USD', type: 'Equity' },
      { symbol: 'UPST', name: 'Upstart Holdings Inc.', sector: 'Financiero', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'GILD', name: 'Gilead Sciences Inc.', sector: 'Salud', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'TEN', name: 'Tenaris', sector: 'Materiales', region: 'AR', currency: 'USD', type: 'Equity' },
      { symbol: 'TX', name: 'Ternium S.A.', sector: 'Materiales', region: 'AR', currency: 'USD', type: 'Equity' },
      { symbol: 'VIST', name: 'Vista Energy S.A.B. de C.V.', sector: 'Energía', region: 'AR', currency: 'USD', type: 'Equity' },
      { symbol: 'LAC', name: 'Lithium Americas Corp', sector: 'Materiales', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'VST', name: 'Vistra Corporation', sector: 'Energía', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'TTE', name: 'TotalEnergies SE', sector: 'Energía', region: 'EU', currency: 'USD', type: 'Equity' },
      { symbol: 'DD', name: 'Dupont de Nemours Inc.', sector: 'Materiales', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'UNP', name: 'Union Pacific Corp.', sector: 'Industrial', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'JCI', name: 'Johnson Controls International', sector: 'Industrial', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'TJX', name: 'TJX Companies Inc.', sector: 'Consumo Discrecional', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'ROKU', name: 'Roku', sector: 'Comunicaciones', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'TWLO', name: 'Twilio Inc.', sector: 'Software', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'TRIP', name: 'Tripadvisor Inc.', sector: 'Consumo Discrecional', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'TCOM', name: 'Trip.com Group Ltd.', sector: 'Consumo Discrecional', region: 'CN', currency: 'USD', type: 'Equity' },
      { symbol: 'T', name: 'AT&T Inc.', sector: 'Comunicaciones', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'TMUS', name: 'T-Mobile US', sector: 'Comunicaciones', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'VZ', name: 'Verizon Communications Inc.', sector: 'Comunicaciones', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'VOD', name: 'Vodafone Group Plc', sector: 'Comunicaciones', region: 'EU', currency: 'USD', type: 'Equity' },
      { symbol: 'STNE', name: 'StoneCo Ltd', sector: 'Financiero', region: 'BR', currency: 'USD', type: 'Equity' },
      { symbol: 'STLA', name: 'Stellantis', sector: 'Consumo Discrecional', region: 'EU', currency: 'USD', type: 'Equity' },
      { symbol: 'SWKS', name: 'Skyworks Solutions', sector: 'Semiconductores', region: 'US', currency: 'USD', type: 'Equity' },
      { symbol: 'SYY', name: 'Sysco Corp.', sector: 'Consumo Básico', region: 'US', currency: 'USD', type: 'Equity' },

      { symbol: 'UL', name: 'Unilever PLC', sector: 'Consumo Básico', region: 'EU', currency: 'USD', type: 'Equity' },

      { symbol: 'TM', name: 'Toyota Motor Corp.', sector: 'Consumo Discrecional', region: 'JP', currency: 'USD', type: 'Equity' },

    ];